<?php

/**
 * @file
 * Provides an API to use the FTS API.
 */

/**
 *  FTS URL
 */
define('FTS_URL', 'http://fts.unocha.org/api/v1/');

function fts_api_get_appeal($id) {
  $xml = simplexml_load_file(FTS_URL . 'appeal/id/' . $id . '.xml');
  return $xml->Appeal;
}

function fts_api_get_funding_by_appeal($id, $groupby = '') {
  $url = FTS_URL . 'funding.xml?appeal=' . $id;
  if (!empty($groupby)) {
    $url .= '&groupby='.$groupby;
  }
  $xml = simplexml_load_file($url);
  return $xml;
}

function fts_api_get_appeal_with_funding($id, $groupby = '') {
  $appeal = fts_api_get_appeal($id);
  $funding = fts_api_get_funding_by_appeal($id, $groupby);
  $appeal->funding = $funding;
  return $appeal;
}
